In [1]:
import numpy as np
import pandas as pd

In [291]:
input = [
    row[0]
    for row
    in np.array(pd.read_csv('aoc_input/aoc8.txt', header = None))
]
input = np.array([
    [
        int(x) 
        for x 
        in str(row)
    ]
    for row in input
])
input

array([[0, 1, 2, ..., 2, 0, 3],
       [3, 2, 1, ..., 1, 0, 3],
       [3, 1, 0, ..., 3, 0, 0],
       ...,
       [1, 0, 0, ..., 2, 3, 0],
       [2, 2, 0, ..., 2, 1, 0],
       [3, 1, 1, ..., 2, 1, 3]])

In [292]:
visible_trees = np.zeros(input.shape)
visible_trees

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [293]:
def see_trees(forest, visible_trees):
    for row in range(len(forest)):
        current_tree_height = -1
        for index in range(len(forest[row])):
            tree_height = forest[row][index]
            if tree_height > current_tree_height:
                visible_trees[row][index] = 1
                current_tree_height = tree_height
    return visible_trees

In [298]:
tree_scores = np.ones(input.shape)
tree_scores

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [299]:
def tree_score(forest, tree_scores):
    for row in range(len(forest)):
        current_tree_height = -1
        largest_tree = 0
        seen_trees = 0
        seen_since_largest = 0
        for index in range(len(forest[row])):
            tree_height = forest[row][index]
            if tree_height >= current_tree_height:
                if tree_height > largest_tree:
                    largest_tree = tree_height
                    seen_since_largest = 0
                    tree_scores[row][index] *= seen_trees
                elif tree_height == largest_tree:
                    tree_scores[row][index] *= int(seen_since_largest)
                    seen_since_largest = 0
                else:
                    tree_scores[row][index] *= int(seen_since_largest)
            else:
                tree_scores[row][index] *= 1
            seen_trees += 1
            seen_since_largest += 1
            current_tree_height = tree_height
    return tree_scores

In [300]:
#part 2
def solve_p2(input, tree_scores):
    for i in range(4):
        tree_scores = tree_score(input, tree_scores)       
        input = np.rot90(input)
        tree_scores = np.rot90(tree_scores)
    return tree_scores
solve_p2(input,tree_scores).max()

436982.0

In [301]:
tree_scores

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [0.000e+00, 1.406e+03, 4.100e+01, ..., 7.000e+01, 3.700e+01,
        0.000e+00],
       [0.000e+00, 1.702e+03, 4.000e+01, ..., 5.040e+03, 3.600e+01,
        0.000e+00],
       ...,
       [0.000e+00, 3.800e+01, 1.240e+02, ..., 2.600e+01, 1.620e+03,
        0.000e+00],
       [0.000e+00, 1.225e+03, 3.200e+01, ..., 1.856e+03, 1.000e+00,
        0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [265]:
#part 1
def solve_p1(input, visible_trees):
    for i in range(4):
        visible_trees = see_trees(input, visible_trees)       
        input = np.rot90(input)
        visible_trees = np.rot90(visible_trees)
    return visible_trees
solve_p1(input,visible_trees).sum()

1711.0